# Generated by Django 4.1.3 on 2023-03-18 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totalunits',
            name='studentgrade_id',
        ),
        migrations.DeleteModel(
            name='OjtStatus',
        ),
        migrations.DeleteModel(
            name='TotalUnits',
        ),
    ]
