# Generated by Django 4.1.3 on 2023-04-04 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, default=1, related_name='related_subjects', to='students.prerequisite'),
        ),
    ]
