# Generated by Django 4.1.3 on 2023-04-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_subjectgrade_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prerequisite',
            name='prerequisite',
            field=models.IntegerField(max_length=50),
        ),
    ]
