# Generated by Django 4.1.3 on 2023-04-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_prerequisite_prerequisite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prerequisite',
            name='prerequisite',
        ),
        migrations.AddField(
            model_name='prerequisite',
            name='prerequisite',
            field=models.ManyToManyField(related_name='subj_prerequisite', to='students.subject'),
        ),
    ]
