# Generated by Django 4.1.3 on 2023-03-22 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('curriculum_year', models.CharField(max_length=200, verbose_name='Curriculum Year')),
            ],
        ),
        migrations.RemoveField(
            model_name='prereq',
            name='prerequisite',
        ),
        migrations.AddField(
            model_name='subject',
            name='curriculum_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='students.curriculum', verbose_name='Curriculum'),
            preserve_default=False,
        ),
    ]
