# Generated by Django 4.1.3 on 2023-03-22 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_curriculum_remove_prereq_prerequisite_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='curriculum_id',
        ),
        migrations.AddField(
            model_name='curriculum',
            name='subjects',
            field=models.ManyToManyField(to='students.subject', verbose_name='Subject'),
        ),
    ]
