# Generated by Django 4.1.3 on 2023-03-22 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_remove_subject_curriculum_id_curriculum_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='added_to_curriculum',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='subjects',
            field=models.ManyToManyField(to='students.subject'),
        ),
    ]
